spring:
   datasource:
      platform: oracle
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@localhost:1521:XE
      username: SPRINGBOOTBOARD
      password: SPRINGBOOTBOARD
---
server:
   port: 8443
   ssl:
      enable: true
      key-store: SpringBootBoard.p12
      key-store-password: SpringBootBoard
      key-store-type: PKCS12
      key-alias: SpringBootBoardAlias
      
      
